### ISSUE TITLE
Tests assume 4k page size

### ISSUE THREAD

**Issue by AdrianBunk** [dignifiedquire/buffer-redux#6]
https://buildd.debian.org/status/fetch.php?pkg=rust-buffer-redux&arch=mips64el&ver=1.0.2-1%2Bb1&stamp=1724714010&raw=0
https://buildd.debian.org/status/fetch.php?pkg=rust-buffer-redux&arch=ppc64el&ver=1.0.2-1%2Bb1&stamp=1724702561&raw=0
https://buildd.debian.org/status/fetch.php?pkg=rust-buffer-redux&arch=loong64&ver=1.0.2-1%2Bb1&stamp=1725300441&raw=0
https://buildd.debian.org/status/fetch.php?pkg=rust-buffer-redux&arch=powerpc&ver=1.0.2-1%2Bb1&stamp=1724703057&raw=0

```
---- ringbuf_tests::test_buffer_new stdout ----
thread 'ringbuf_tests::test_buffer_new' panicked at src/ringbuf_tests.rs:39:5:
assertion `left == right` failed
  left: 65536
 right: 8192
...
---- ringbuf_tests::test_buffer_with_cap stdout ----
thread 'ringbuf_tests::test_buffer_with_cap' panicked at src/ringbuf_tests.rs:46:5:
assertion `left == right` failed
  left: 65536
 right: 4096
```

The page size is a configuration option for the kernel, this is not something that is fixed at build time or even always 4k.

Different hardware might use different kernel sizes (e.g. MIPS in Debian).

Distributions even provide kernel images with different page sizes for the same hardware:
https://ubuntu.com/server/docs/choosing-between-the-arm64-and-arm64-largemem-installer-options

This makes code like the following incorrect:
```
    // test rounding up to page size
    let buf = Buffer::with_capacity_ringbuf(64);
    assert_capacity!(buf, 4 * 1024);
```

I haven't checked whether these are only buggy tests, or whether there are also bugs in the actual code.

**Comment by dkg** [comment]
In debian, we've modified this test with the following patch:

```diff
Index: buffer-redux/src/ringbuf_tests.rs
===================================================================
--- buffer-redux.orig/src/ringbuf_tests.rs
+++ buffer-redux/src/ringbuf_tests.rs
@@ -28,7 +28,11 @@ macro_rules! assert_capacity {
             // Macos' minimum allocation size is sometimes? 16K
             assert!(cap == $cap || cap == ::std::cmp::max(16 * 1024, $cap));
         } else {
-            assert_eq!(cap, $cap);
+            // some linux systems have larger pages, we assert that
+            // either the capacity is the capacity requested, or
+            // that the capacity is larger than requested and is
+            // a power of two.
+            assert!((cap == $cap) || ((cap >= $cap) && ((cap & (cap - 1)) == 0 )));
         }
     };
 }
```
